version: '3.8'
volumes:
  db-store:
services:
  web:
    image: nginx:1.19.4-alpine
    container_name: php8_web_server_container
    volumes:
      - ./Infrastructure/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./App/php8/public:/var/www/app/public
    links:
      - application
    depends_on:
      - application
    ports:
      - "8000:80"
  application:
    container_name: php8_container
    build:
      context: .
      dockerfile: ./Infrastructure/php/Dockerfile
    volumes:
      - ./App/php8:/var/www/app
      - ./Infrastructure/php/php.ini:/usr/local/etc/php/php.ini
    links:
      - database
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_DATABASE=php8
      - DB_USERNAME=root
      - DB_PASSWORD=root
  database:
    container_name: php8_database_container
    build:
      context: .
      dockerfile: ./Infrastructure/mysql/Dockerfile
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=php8
      - MYSQL_USER=root
      - MYSQL_PASSWORD=user
      - MYSQL_ROOT_PASSWORD=root
